name: EduMap
description: This is an educational project about helping students make better decisions.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  eva_icons_flutter: ^2.0.0
  flutter_statusbarcolor: ^0.2.3
  flutter_datetime_picker: ^1.2.8
  division: ^0.8.4+1
  flare_flutter: ^1.7.3
  auto_size_text: ^2.1.0
  cached_network_image: ^1.1.3
  # Service locator
  get_it: ^3.0.3
  # Bloc for state management
  flutter_bloc: ^2.0.0
  #flutter_bloc: ^0.21.0
  # Value equality
  equatable: ^1.0.0
  # Functional programming thingies
  dartz: ^0.8.8
  # Check connectivity
  connectivity: ^0.4.5+3
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^0.5.4+5
  # Lunch Urls
  url_launcher: ^5.2.5
  # Built Value
  built_value: ^6.7.1
  built_collection: ^4.2.2
  # Flutter String Encryption
  password: ^1.0.0
  # Map
  flutter_map: ^0.7.3
  # Location
  location: ^1.3.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  build_runner: ^1.7.0
  built_value_generator: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/img/checkmark.png
    - assets/img/educationMapTitle.PNG
    - assets/img/eduMapTitle.PNG
    - assets/img/request_pic.png
    - assets/img/logo.png
    - assets/img/offline.png
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
    - family: Titillium
      fonts:
        - asset: assets/fonts/Titillium_Web/TitilliumWeb-Black.ttf
        - asset: assets/fonts/Titillium_Web/TitilliumWeb-Bold.ttf
        - asset: assets/fonts/Titillium_Web/TitilliumWeb-Light.ttf
        - asset: assets/fonts/Titillium_Web/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/Titillium_Web/TitilliumWeb-Italic.ttf
